services:
  - type: web
    name: roadpolice-bot
    env: python
    buildCommand: ./render-build.sh
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_BASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_TABLE
        value: users
      - key: TRACK_INTERVAL_MINUTES
        value: "120"
      - key: LOOKAHEAD_DAYS
        value: "30"
